// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc_Day__4.Context;

#nullable disable

namespace Mvc_Day__4.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250727224005_Validation")]
    partial class Validation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvc_Day__4.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "SD"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "UI"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Mob"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptName = "Network"
                        },
                        new
                        {
                            DeptId = 5,
                            DeptName = "AI"
                        },
                        new
                        {
                            DeptId = 6,
                            DeptName = "Cyber Security"
                        },
                        new
                        {
                            DeptId = 7,
                            DeptName = "Embedded Systems"
                        },
                        new
                        {
                            DeptId = 8,
                            DeptName = "Game Development"
                        },
                        new
                        {
                            DeptId = 9,
                            DeptName = "Data Science"
                        },
                        new
                        {
                            DeptId = 10,
                            DeptName = "Cloud Computing"
                        },
                        new
                        {
                            DeptId = 11,
                            DeptName = "Robotics"
                        },
                        new
                        {
                            DeptId = 12,
                            DeptName = "Bioinformatics"
                        },
                        new
                        {
                            DeptId = 13,
                            DeptName = "DevOps"
                        },
                        new
                        {
                            DeptId = 14,
                            DeptName = "Technical Support"
                        },
                        new
                        {
                            DeptId = 15,
                            DeptName = "ERP Systems"
                        });
                });

            modelBuilder.Entity("Mvc_Day__4.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("EmployeeName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            Age = 25,
                            DepartmentId = 1,
                            Email = "ahmed.ali@example.com",
                            Name = "Ahmed Ali",
                            Password = "pass1234",
                            Salary = 5000.00m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            Age = 30,
                            DepartmentId = 2,
                            Email = "mona.said@example.com",
                            Name = "Mona Said",
                            Password = "mona456",
                            Salary = 7000.00m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria",
                            Age = 28,
                            DepartmentId = 3,
                            Email = "youssef.g@example.com",
                            Name = "Youssef Gamal",
                            Password = "you12345",
                            Salary = 6200.00m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura",
                            Age = 22,
                            DepartmentId = 1,
                            Email = "sara.fathy@example.com",
                            Name = "Sara Fathy",
                            Password = "sara987",
                            Salary = 4500.00m
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tanta",
                            Age = 35,
                            DepartmentId = 2,
                            Email = "khaled.n@example.com",
                            Name = "Khaled Nour",
                            Password = "khaledpw",
                            Salary = 9500.00m
                        },
                        new
                        {
                            Id = 6,
                            Address = "Zagazig",
                            Age = 27,
                            DepartmentId = 3,
                            Email = "nour.hassan@example.com",
                            Name = "Nour Hassan",
                            Password = "nourpass",
                            Salary = 7100.00m
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ismailia",
                            Age = 29,
                            DepartmentId = 1,
                            Email = "omar.adel@example.com",
                            Name = "Omar Adel",
                            Password = "omar123",
                            Salary = 8000.00m
                        },
                        new
                        {
                            Id = 8,
                            Address = "Aswan",
                            Age = 32,
                            DepartmentId = 2,
                            Email = "laila.samir@example.com",
                            Name = "Laila Samir",
                            Password = "laila321",
                            Salary = 8800.00m
                        },
                        new
                        {
                            Id = 9,
                            Address = "Fayoum",
                            Age = 26,
                            DepartmentId = 3,
                            Email = "hassan.omar@example.com",
                            Name = "Hassan Omar",
                            Password = "hassanpw",
                            Salary = 5700.00m
                        },
                        new
                        {
                            Id = 10,
                            Address = "Luxor",
                            Age = 24,
                            DepartmentId = 4,
                            Email = "dina.nabil@example.com",
                            Name = "Dina Nabil",
                            Password = "dina444",
                            Salary = 5200.00m
                        },
                        new
                        {
                            Id = 11,
                            Address = "Cairo",
                            Age = 23,
                            DepartmentId = 5,
                            Email = "mahmoud.t@example.com",
                            Name = "Mahmoud Tarek",
                            Password = "mahmoud23",
                            Salary = 4800.00m
                        },
                        new
                        {
                            Id = 12,
                            Address = "Giza",
                            Age = 31,
                            DepartmentId = 6,
                            Email = "fatma.salah@example.com",
                            Name = "Fatma Salah",
                            Password = "fatma987",
                            Salary = 7700.00m
                        },
                        new
                        {
                            Id = 13,
                            Address = "Alexandria",
                            Age = 27,
                            DepartmentId = 7,
                            Email = "ali.nasser@example.com",
                            Name = "Ali Nasser",
                            Password = "alinasser",
                            Salary = 6100.00m
                        },
                        new
                        {
                            Id = 14,
                            Address = "Cairo",
                            Age = 22,
                            DepartmentId = 8,
                            Email = "heba.hany@example.com",
                            Name = "Heba Hany",
                            Password = "heba22",
                            Salary = 4300.00m
                        },
                        new
                        {
                            Id = 15,
                            Address = "Suez",
                            Age = 34,
                            DepartmentId = 9,
                            Email = "mostafa.adel@example.com",
                            Name = "Mostafa Adel",
                            Password = "mostafaa",
                            Salary = 9200.00m
                        },
                        new
                        {
                            Id = 16,
                            Address = "Banha",
                            Age = 28,
                            DepartmentId = 10,
                            Email = "nada.wael@example.com",
                            Name = "Nada Wael",
                            Password = "nada456",
                            Salary = 6800.00m
                        },
                        new
                        {
                            Id = 17,
                            Address = "Minya",
                            Age = 26,
                            DepartmentId = 11,
                            Email = "tamer.younis@example.com",
                            Name = "Tamer Younis",
                            Password = "tamerpw",
                            Salary = 5900.00m
                        },
                        new
                        {
                            Id = 18,
                            Address = "Qena",
                            Age = 30,
                            DepartmentId = 12,
                            Email = "rana.sameh@example.com",
                            Name = "Rana Sameh",
                            Password = "rana123",
                            Salary = 8600.00m
                        },
                        new
                        {
                            Id = 19,
                            Address = "Assiut",
                            Age = 25,
                            DepartmentId = 13,
                            Email = "islam.ayman@example.com",
                            Name = "Islam Ayman",
                            Password = "islam321",
                            Salary = 5300.00m
                        },
                        new
                        {
                            Id = 20,
                            Address = "Sohag",
                            Age = 29,
                            DepartmentId = 14,
                            Email = "salma.fares@example.com",
                            Name = "Salma Fares",
                            Password = "salma987",
                            Salary = 7500.00m
                        });
                });

            modelBuilder.Entity("Mvc_Day__4.Models.Student", b =>
                {
                    b.HasOne("Mvc_Day__4.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Mvc_Day__4.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
