// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc_Day__4.Context;

#nullable disable

namespace Mvc_Day__4.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250727213943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvc_Day__4.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "SD"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "UI"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Mob"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptName = "Network"
                        });
                });

            modelBuilder.Entity("Mvc_Day__4.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            Age = 25,
                            DepartmentId = 1,
                            Email = "ahmed.ali@example.com",
                            Name = "Ahmed Ali",
                            Password = "pass1234",
                            Salary = 5000.00m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            Age = 30,
                            DepartmentId = 2,
                            Email = "mona.said@example.com",
                            Name = "Mona Said",
                            Password = "mona456",
                            Salary = 7000.00m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria",
                            Age = 28,
                            DepartmentId = 3,
                            Email = "youssef.g@example.com",
                            Name = "Youssef Gamal",
                            Password = "you12345",
                            Salary = 6200.00m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura",
                            Age = 22,
                            DepartmentId = 1,
                            Email = "sara.fathy@example.com",
                            Name = "Sara Fathy",
                            Password = "sara987",
                            Salary = 4500.00m
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tanta",
                            Age = 35,
                            DepartmentId = 2,
                            Email = "khaled.n@example.com",
                            Name = "Khaled Nour",
                            Password = "khaledpw",
                            Salary = 9500.00m
                        },
                        new
                        {
                            Id = 6,
                            Address = "Zagazig",
                            Age = 27,
                            DepartmentId = 3,
                            Email = "nour.hassan@example.com",
                            Name = "Nour Hassan",
                            Password = "nourpass",
                            Salary = 7100.00m
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ismailia",
                            Age = 29,
                            DepartmentId = 1,
                            Email = "omar.adel@example.com",
                            Name = "Omar Adel",
                            Password = "omar123",
                            Salary = 8000.00m
                        },
                        new
                        {
                            Id = 8,
                            Address = "Aswan",
                            Age = 32,
                            DepartmentId = 2,
                            Email = "laila.samir@example.com",
                            Name = "Laila Samir",
                            Password = "laila321",
                            Salary = 8800.00m
                        },
                        new
                        {
                            Id = 9,
                            Address = "Fayoum",
                            Age = 26,
                            DepartmentId = 3,
                            Email = "hassan.omar@example.com",
                            Name = "Hassan Omar",
                            Password = "hassanpw",
                            Salary = 5700.00m
                        },
                        new
                        {
                            Id = 10,
                            Address = "Luxor",
                            Age = 24,
                            DepartmentId = 4,
                            Email = "dina.nabil@example.com",
                            Name = "Dina Nabil",
                            Password = "dina444",
                            Salary = 5200.00m
                        });
                });

            modelBuilder.Entity("Mvc_Day__4.Models.Student", b =>
                {
                    b.HasOne("Mvc_Day__4.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Mvc_Day__4.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
